# Generated by Django 5.1.1 on 2024-09-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='fone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='mail',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
