# Generated by Django 5.1.1 on 2024-09-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_clientes', '0002_eventos_fone_eventos_mail_eventos_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='mail',
            new_name='email',
        ),
    ]
